#include <iostream>
#include <memory>
#include <chrono>
#include <thread>
#include <csignal>
#include <atomic>

// Include your custom background worker class structures
#include "../../cGenericGrpcWorker.h"
#include "gRPCAnalytics.grpc.pb.h"               

// 1. Map your generated protobuf types to your structural trait configuration template
using AnalyticsTraits = gRPCServiceTraits<
    analytics::AnalyticsService,
    analytics::MetricRequest,
    analytics::MetricResponse>;

// 2. Derive your worker implementation from the generic CRTP gRPC engine base class
class cAnalyticsWorker final : public cGenericGrpcWorker<cAnalyticsWorker, AnalyticsTraits>
{
public:
    // Pull the generic parent constructor forward
    using cGenericGrpcWorker::cGenericGrpcWorker;

    // Define the specific RPC binder method pointer generated by protoc
    static constexpr RequestRpcFn GetRpcBinding()
    {
        return &analytics::AnalyticsService::AsyncService::RequestSendMetric;
    }

    // Implement your core business logic routine when an event arrives
    void OnExecuteRpc(grpc::ServerContext &ctx,
                      const analytics::MetricRequest &request,
                      analytics::MetricResponse &reply,
                      grpc::ServerAsyncResponseWriter<analytics::MetricResponse> &responder,
                      void *tag)
    {

        // Quick extraction of incoming binary payload fields
        std::cout << "[" << name() << "] Received processing payload from Device: "
                  << request.device_id() << " | Value: " << request.reading_value() << "\n";

        // Build the fast binary response objects
        reply.set_success(true);
        reply.set_message("Payload processed successfully via CRTP abstraction.");

        // Finalize the connection handling
        responder.Finish(reply, grpc::Status::OK, tag);
    }
};

// 3. Simple atomic flag to safely process Apple/OS Unix termination signals
namespace
{
    std::atomic<bool> g_shutdownRequested{false};
}

void SignalHandler(int signal)
{
    if (signal == SIGINT || signal == SIGTERM)
    {
        g_shutdownRequested.store(true, std::memory_order_release);
    }
}

// 4. Application Runtime Entry Point
int main()
{
    // Register Unix termination signal handlers for graceful shutdowns (Ctrl+C handling)
    std::signal(SIGINT, SignalHandler);
    std::signal(SIGTERM, SignalHandler);

    std::cout << "--- Initialising Low-Latency C++ gRPC Service Framework ---\n";

    const std::string server_address("0.0.0.0:50051");

    // Allocate the specific compiled template background engine instance
    auto workerService = std::make_unique<cAnalyticsWorker>("AnalyticsWorkerEngine", server_address);

    // Boot up the native operating system background thread context managed by cBaseWorker_V2
    std::cout << "Starting application worker engine threads...\n";
    if (!workerService->startThread(std::chrono::milliseconds(3000)))
    {
        std::cerr << "CRITICAL ERROR: Failed to bind to target socket: " << server_address << "\n";
        return EXIT_FAILURE;
    }

    std::cout << "Engine successfully running. Press Ctrl+C to terminate cleanly.\n";

    // Standard application event orchestrator loop
    while (!g_shutdownRequested.load(std::memory_order_acquire))
    {
        // Monitor worker lifecycle sanity health metrics
        auto lastHb = workerService->lastHeartbeat();
        auto hbPeriod = workerService->heartBeatPeriod().count();

        std::cout << "[Monitor] Engine Thread State: "
                  << static_cast<int>(workerService->getState())
                  << " | Last Period: " << hbPeriod << "ms\n";

        // Check if internal background panics or crashes happened inside run() execution paths
        if (workerService->lastUnhandledException())
        {
            std::cerr << "CRITICAL ERROR: Worker background event loop crashed due to unhandled exception!\n";
            break;
        }

        std::this_thread::sleep_for(std::chrono::seconds(5));
    }

    // 5. Cooperative RAII Shutdown Orchestration Execution
    std::cout << "\nGraceful shutdown signal caught. Stopping service nodes...\n";

    // cBaseWorker_V2 triggers stopTriggered() hooks -> drains gRPC cues -> joins OS threads
    workerService->stopThreadAndJoin(std::chrono::milliseconds(5000));

    std::cout << "Application state components completely destructed. Clean exit achieved.\n";
    return EXIT_SUCCESS;
}
