// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: gRPCAnalytics.proto
#ifndef GRPC_gRPCAnalytics_2eproto__INCLUDED
#define GRPC_gRPCAnalytics_2eproto__INCLUDED

#include "gRPCAnalytics.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>

namespace analytics
{

  // The service defining the remote function
  class AnalyticsService final
  {
  public:
    static constexpr char const *service_full_name()
    {
      return "analytics.AnalyticsService";
    }
    class StubInterface
    {
    public:
      virtual ~StubInterface() {}
      virtual ::grpc::Status SendMetric(::grpc::ClientContext *context, const ::analytics::MetricRequest &request, ::analytics::MetricResponse *response) = 0;
      std::unique_ptr<::grpc::ClientAsyncResponseReaderInterface<::analytics::MetricResponse>> AsyncSendMetric(::grpc::ClientContext *context, const ::analytics::MetricRequest &request, ::grpc::CompletionQueue *cq)
      {
        return std::unique_ptr<::grpc::ClientAsyncResponseReaderInterface<::analytics::MetricResponse>>(AsyncSendMetricRaw(context, request, cq));
      }
      std::unique_ptr<::grpc::ClientAsyncResponseReaderInterface<::analytics::MetricResponse>> PrepareAsyncSendMetric(::grpc::ClientContext *context, const ::analytics::MetricRequest &request, ::grpc::CompletionQueue *cq)
      {
        return std::unique_ptr<::grpc::ClientAsyncResponseReaderInterface<::analytics::MetricResponse>>(PrepareAsyncSendMetricRaw(context, request, cq));
      }
      class async_interface
      {
      public:
        virtual ~async_interface() {}
        virtual void SendMetric(::grpc::ClientContext *context, const ::analytics::MetricRequest *request, ::analytics::MetricResponse *response, std::function<void(::grpc::Status)>) = 0;
        virtual void SendMetric(::grpc::ClientContext *context, const ::analytics::MetricRequest *request, ::analytics::MetricResponse *response, ::grpc::ClientUnaryReactor *reactor) = 0;
      };
      typedef class async_interface experimental_async_interface;
      virtual class async_interface *async() { return nullptr; }
      class async_interface *experimental_async() { return async(); }

    private:
      virtual ::grpc::ClientAsyncResponseReaderInterface<::analytics::MetricResponse> *AsyncSendMetricRaw(::grpc::ClientContext *context, const ::analytics::MetricRequest &request, ::grpc::CompletionQueue *cq) = 0;
      virtual ::grpc::ClientAsyncResponseReaderInterface<::analytics::MetricResponse> *PrepareAsyncSendMetricRaw(::grpc::ClientContext *context, const ::analytics::MetricRequest &request, ::grpc::CompletionQueue *cq) = 0;
    };
    class Stub final : public StubInterface
    {
    public:
      Stub(const std::shared_ptr<::grpc::ChannelInterface> &channel, const ::grpc::StubOptions &options = ::grpc::StubOptions());
      ::grpc::Status SendMetric(::grpc::ClientContext *context, const ::analytics::MetricRequest &request, ::analytics::MetricResponse *response) override;
      std::unique_ptr<::grpc::ClientAsyncResponseReader<::analytics::MetricResponse>> AsyncSendMetric(::grpc::ClientContext *context, const ::analytics::MetricRequest &request, ::grpc::CompletionQueue *cq)
      {
        return std::unique_ptr<::grpc::ClientAsyncResponseReader<::analytics::MetricResponse>>(AsyncSendMetricRaw(context, request, cq));
      }
      std::unique_ptr<::grpc::ClientAsyncResponseReader<::analytics::MetricResponse>> PrepareAsyncSendMetric(::grpc::ClientContext *context, const ::analytics::MetricRequest &request, ::grpc::CompletionQueue *cq)
      {
        return std::unique_ptr<::grpc::ClientAsyncResponseReader<::analytics::MetricResponse>>(PrepareAsyncSendMetricRaw(context, request, cq));
      }
      class async final : public StubInterface::async_interface
      {
      public:
        void SendMetric(::grpc::ClientContext *context, const ::analytics::MetricRequest *request, ::analytics::MetricResponse *response, std::function<void(::grpc::Status)>) override;
        void SendMetric(::grpc::ClientContext *context, const ::analytics::MetricRequest *request, ::analytics::MetricResponse *response, ::grpc::ClientUnaryReactor *reactor) override;

      private:
        friend class Stub;
        explicit async(Stub *stub) : stub_(stub) {}
        Stub *stub() { return stub_; }
        Stub *stub_;
      };
      class async *async() override { return &async_stub_; }

    private:
      std::shared_ptr<::grpc::ChannelInterface> channel_;
      class async async_stub_{this};
      ::grpc::ClientAsyncResponseReader<::analytics::MetricResponse> *AsyncSendMetricRaw(::grpc::ClientContext *context, const ::analytics::MetricRequest &request, ::grpc::CompletionQueue *cq) override;
      ::grpc::ClientAsyncResponseReader<::analytics::MetricResponse> *PrepareAsyncSendMetricRaw(::grpc::ClientContext *context, const ::analytics::MetricRequest &request, ::grpc::CompletionQueue *cq) override;
      const ::grpc::internal::RpcMethod rpcmethod_SendMetric_;
    };
    static std::unique_ptr<Stub> NewStub(const std::shared_ptr<::grpc::ChannelInterface> &channel, const ::grpc::StubOptions &options = ::grpc::StubOptions());

    class Service : public ::grpc::Service
    {
    public:
      Service();
      virtual ~Service();
      virtual ::grpc::Status SendMetric(::grpc::ServerContext *context, const ::analytics::MetricRequest *request, ::analytics::MetricResponse *response);
    };
    template <class BaseClass>
    class WithAsyncMethod_SendMetric : public BaseClass
    {
    private:
      void BaseClassMustBeDerivedFromService(const Service * /*service*/) {}

    public:
      WithAsyncMethod_SendMetric()
      {
        ::grpc::Service::MarkMethodAsync(0);
      }
      ~WithAsyncMethod_SendMetric() override
      {
        BaseClassMustBeDerivedFromService(this);
      }
      // disable synchronous version of this method
      ::grpc::Status SendMetric(::grpc::ServerContext * /*context*/, const ::analytics::MetricRequest * /*request*/, ::analytics::MetricResponse * /*response*/) override
      {
        abort();
        return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
      }
      void RequestSendMetric(::grpc::ServerContext *context, ::analytics::MetricRequest *request, ::grpc::ServerAsyncResponseWriter<::analytics::MetricResponse> *response, ::grpc::CompletionQueue *new_call_cq, ::grpc::ServerCompletionQueue *notification_cq, void *tag)
      {
        ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
      }
    };
    typedef WithAsyncMethod_SendMetric<Service> AsyncService;
    template <class BaseClass>
    class WithCallbackMethod_SendMetric : public BaseClass
    {
    private:
      void BaseClassMustBeDerivedFromService(const Service * /*service*/) {}

    public:
      WithCallbackMethod_SendMetric()
      {
        ::grpc::Service::MarkMethodCallback(0,
                                            new ::grpc::internal::CallbackUnaryHandler<::analytics::MetricRequest, ::analytics::MetricResponse>(
                                                [this](
                                                    ::grpc::CallbackServerContext *context, const ::analytics::MetricRequest *request, ::analytics::MetricResponse *response)
                                                { return this->SendMetric(context, request, response); }));
      }
      void SetMessageAllocatorFor_SendMetric(
          ::grpc::MessageAllocator<::analytics::MetricRequest, ::analytics::MetricResponse> *allocator)
      {
        ::grpc::internal::MethodHandler *const handler = ::grpc::Service::GetHandler(0);
        static_cast<::grpc::internal::CallbackUnaryHandler<::analytics::MetricRequest, ::analytics::MetricResponse> *>(handler)
            ->SetMessageAllocator(allocator);
      }
      ~WithCallbackMethod_SendMetric() override
      {
        BaseClassMustBeDerivedFromService(this);
      }
      // disable synchronous version of this method
      ::grpc::Status SendMetric(::grpc::ServerContext * /*context*/, const ::analytics::MetricRequest * /*request*/, ::analytics::MetricResponse * /*response*/) override
      {
        abort();
        return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
      }
      virtual ::grpc::ServerUnaryReactor *SendMetric(
          ::grpc::CallbackServerContext * /*context*/, const ::analytics::MetricRequest * /*request*/, ::analytics::MetricResponse * /*response*/) { return nullptr; }
    };
    typedef WithCallbackMethod_SendMetric<Service> CallbackService;
    typedef CallbackService ExperimentalCallbackService;
    template <class BaseClass>
    class WithGenericMethod_SendMetric : public BaseClass
    {
    private:
      void BaseClassMustBeDerivedFromService(const Service * /*service*/) {}

    public:
      WithGenericMethod_SendMetric()
      {
        ::grpc::Service::MarkMethodGeneric(0);
      }
      ~WithGenericMethod_SendMetric() override
      {
        BaseClassMustBeDerivedFromService(this);
      }
      // disable synchronous version of this method
      ::grpc::Status SendMetric(::grpc::ServerContext * /*context*/, const ::analytics::MetricRequest * /*request*/, ::analytics::MetricResponse * /*response*/) override
      {
        abort();
        return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
      }
    };
    template <class BaseClass>
    class WithRawMethod_SendMetric : public BaseClass
    {
    private:
      void BaseClassMustBeDerivedFromService(const Service * /*service*/) {}

    public:
      WithRawMethod_SendMetric()
      {
        ::grpc::Service::MarkMethodRaw(0);
      }
      ~WithRawMethod_SendMetric() override
      {
        BaseClassMustBeDerivedFromService(this);
      }
      // disable synchronous version of this method
      ::grpc::Status SendMetric(::grpc::ServerContext * /*context*/, const ::analytics::MetricRequest * /*request*/, ::analytics::MetricResponse * /*response*/) override
      {
        abort();
        return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
      }
      void RequestSendMetric(::grpc::ServerContext *context, ::grpc::ByteBuffer *request, ::grpc::ServerAsyncResponseWriter<::grpc::ByteBuffer> *response, ::grpc::CompletionQueue *new_call_cq, ::grpc::ServerCompletionQueue *notification_cq, void *tag)
      {
        ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
      }
    };
    template <class BaseClass>
    class WithRawCallbackMethod_SendMetric : public BaseClass
    {
    private:
      void BaseClassMustBeDerivedFromService(const Service * /*service*/) {}

    public:
      WithRawCallbackMethod_SendMetric()
      {
        ::grpc::Service::MarkMethodRawCallback(0,
                                               new ::grpc::internal::CallbackUnaryHandler<::grpc::ByteBuffer, ::grpc::ByteBuffer>(
                                                   [this](
                                                       ::grpc::CallbackServerContext *context, const ::grpc::ByteBuffer *request, ::grpc::ByteBuffer *response)
                                                   { return this->SendMetric(context, request, response); }));
      }
      ~WithRawCallbackMethod_SendMetric() override
      {
        BaseClassMustBeDerivedFromService(this);
      }
      // disable synchronous version of this method
      ::grpc::Status SendMetric(::grpc::ServerContext * /*context*/, const ::analytics::MetricRequest * /*request*/, ::analytics::MetricResponse * /*response*/) override
      {
        abort();
        return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
      }
      virtual ::grpc::ServerUnaryReactor *SendMetric(
          ::grpc::CallbackServerContext * /*context*/, const ::grpc::ByteBuffer * /*request*/, ::grpc::ByteBuffer * /*response*/) { return nullptr; }
    };
    template <class BaseClass>
    class WithStreamedUnaryMethod_SendMetric : public BaseClass
    {
    private:
      void BaseClassMustBeDerivedFromService(const Service * /*service*/) {}

    public:
      WithStreamedUnaryMethod_SendMetric()
      {
        ::grpc::Service::MarkMethodStreamed(0,
                                            new ::grpc::internal::StreamedUnaryHandler<
                                                ::analytics::MetricRequest, ::analytics::MetricResponse>(
                                                [this](::grpc::ServerContext *context,
                                                       ::grpc::ServerUnaryStreamer<
                                                           ::analytics::MetricRequest, ::analytics::MetricResponse> *streamer)
                                                {
                                                  return this->StreamedSendMetric(context,
                                                                                  streamer);
                                                }));
      }
      ~WithStreamedUnaryMethod_SendMetric() override
      {
        BaseClassMustBeDerivedFromService(this);
      }
      // disable regular version of this method
      ::grpc::Status SendMetric(::grpc::ServerContext * /*context*/, const ::analytics::MetricRequest * /*request*/, ::analytics::MetricResponse * /*response*/) override
      {
        abort();
        return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
      }
      // replace default version of method with streamed unary
      virtual ::grpc::Status StreamedSendMetric(::grpc::ServerContext *context, ::grpc::ServerUnaryStreamer<::analytics::MetricRequest, ::analytics::MetricResponse> *server_unary_streamer) = 0;
    };
    typedef WithStreamedUnaryMethod_SendMetric<Service> StreamedUnaryService;
    typedef Service SplitStreamedService;
    typedef WithStreamedUnaryMethod_SendMetric<Service> StreamedService;
  };

} // namespace analytics

#include <grpcpp/ports_undef.inc>
#endif // GRPC_gRPCAnalytics_2eproto__INCLUDED
