// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: gRPCAnalytics.proto

#include "gRPCAnalytics.pb.h"
#include "gRPCAnalytics.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>
namespace analytics
{

  static const char *AnalyticsService_method_names[] = {
      "/analytics.AnalyticsService/SendMetric",
  };

  std::unique_ptr<AnalyticsService::Stub> AnalyticsService::NewStub(const std::shared_ptr<::grpc::ChannelInterface> &channel, const ::grpc::StubOptions &options)
  {
    (void)options;
    std::unique_ptr<AnalyticsService::Stub> stub(new AnalyticsService::Stub(channel, options));
    return stub;
  }

  AnalyticsService::Stub::Stub(const std::shared_ptr<::grpc::ChannelInterface> &channel, const ::grpc::StubOptions &options)
      : channel_(channel), rpcmethod_SendMetric_(AnalyticsService_method_names[0], options.suffix_for_stats(), ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {
  }

  ::grpc::Status AnalyticsService::Stub::SendMetric(::grpc::ClientContext *context, const ::analytics::MetricRequest &request, ::analytics::MetricResponse *response)
  {
    return ::grpc::internal::BlockingUnaryCall<::analytics::MetricRequest, ::analytics::MetricResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SendMetric_, context, request, response);
  }

  void AnalyticsService::Stub::async::SendMetric(::grpc::ClientContext *context, const ::analytics::MetricRequest *request, ::analytics::MetricResponse *response, std::function<void(::grpc::Status)> f)
  {
    ::grpc::internal::CallbackUnaryCall<::analytics::MetricRequest, ::analytics::MetricResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SendMetric_, context, request, response, std::move(f));
  }

  void AnalyticsService::Stub::async::SendMetric(::grpc::ClientContext *context, const ::analytics::MetricRequest *request, ::analytics::MetricResponse *response, ::grpc::ClientUnaryReactor *reactor)
  {
    ::grpc::internal::ClientCallbackUnaryFactory::Create<::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SendMetric_, context, request, response, reactor);
  }

  ::grpc::ClientAsyncResponseReader<::analytics::MetricResponse> *AnalyticsService::Stub::PrepareAsyncSendMetricRaw(::grpc::ClientContext *context, const ::analytics::MetricRequest &request, ::grpc::CompletionQueue *cq)
  {
    return ::grpc::internal::ClientAsyncResponseReaderHelper::Create<::analytics::MetricResponse, ::analytics::MetricRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SendMetric_, context, request);
  }

  ::grpc::ClientAsyncResponseReader<::analytics::MetricResponse> *AnalyticsService::Stub::AsyncSendMetricRaw(::grpc::ClientContext *context, const ::analytics::MetricRequest &request, ::grpc::CompletionQueue *cq)
  {
    auto *result =
        this->PrepareAsyncSendMetricRaw(context, request, cq);
    result->StartCall();
    return result;
  }

  AnalyticsService::Service::Service()
  {
    AddMethod(new ::grpc::internal::RpcServiceMethod(
        AnalyticsService_method_names[0],
        ::grpc::internal::RpcMethod::NORMAL_RPC,
        new ::grpc::internal::RpcMethodHandler<AnalyticsService::Service, ::analytics::MetricRequest, ::analytics::MetricResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
            [](AnalyticsService::Service *service,
               ::grpc::ServerContext *ctx,
               const ::analytics::MetricRequest *req,
               ::analytics::MetricResponse *resp)
            {
              return service->SendMetric(ctx, req, resp);
            },
            this)));
  }

  AnalyticsService::Service::~Service()
  {
  }

  ::grpc::Status AnalyticsService::Service::SendMetric(::grpc::ServerContext *context, const ::analytics::MetricRequest *request, ::analytics::MetricResponse *response)
  {
    (void)context;
    (void)request;
    (void)response;
    return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
  }

} // namespace analytics
#include <grpcpp/ports_undef.inc>
