// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: gRPCAnalytics.proto
// Protobuf C++ Version: 7.36.0

#include "gRPCAnalytics.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/internal_visibility.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
#ifdef PROTOBUF_MESSAGE_GLOBALS
namespace
{
  PROTOBUF_CONSTINIT ::google::protobuf::internal::ReflectionData
      file_reflection_data[] = {
          // ::analytics::MetricRequest
          {
              &::_pbi::kDescriptorMethods,
              &::descriptor_table_gRPCAnalytics_2eproto,
              /* tracker*/ nullptr,
          },
          // ::analytics::MetricResponse
          {
              &::_pbi::kDescriptorMethods,
              &::descriptor_table_gRPCAnalytics_2eproto,
              /* tracker*/ nullptr,
          },
  };
} // namespace
#endif
namespace analytics
{
  class MetricResponse::_Internal
  {
  public:
    using HasBits = decltype(::std::declval<MetricResponse>()._impl_._has_bits_);
    static constexpr ::int32_t kHasBitsOffset =
        8 * PROTOBUF_FIELD_OFFSET(MetricResponse, _impl_._has_bits_);
  };

  constexpr MetricResponse::ParseTableT_ MetricResponse::InternalGenerateParseTable_(const ::_pbi::ClassData *class_data)
  {
    return ParseTableT_{
        {
            PROTOBUF_FIELD_OFFSET(MetricResponse, _impl_._has_bits_),
            0, // no _extensions_
            2,
            8, // max_field_number, fast_idx_mask
            offsetof(ParseTableT_, field_lookup_table),
            4294967292, // skipmap
            offsetof(ParseTableT_, field_entries),
            2,                                   // num_field_entries
            0,                                   // num_aux_entries
            offsetof(ParseTableT_, field_names), // no aux_entries
            class_data,
            nullptr,                           // post_loop_handler
            ::_pbi::TcParser::MpUnknownFields, // fallback
#ifdef PROTOBUF_PREFETCH_PARSE_TABLE
            ::_pbi::TcParser::GetTable<::analytics::MetricResponse>(), // to_prefetch
#endif                                                                 // PROTOBUF_PREFETCH_PARSE_TABLE
        },
        {{
            // string message = 2;
            {::_pbi::TcParser::FastUS1,
             {18, 0, 0,
              PROTOBUF_FIELD_OFFSET(MetricResponse, _impl_.message_)}},
            // bool success = 1;
            {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(MetricResponse, _impl_.success_), 1>(),
             {8, 1, 0,
              PROTOBUF_FIELD_OFFSET(MetricResponse, _impl_.success_)}},
        }},
        {{65535, 65535}},
        {{
            // bool success = 1;
            {PROTOBUF_FIELD_OFFSET(MetricResponse, _impl_.success_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kBool)},
            // string message = 2;
            {PROTOBUF_FIELD_OFFSET(MetricResponse, _impl_.message_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
        }},
        // no aux_entries
        {{"\30\0\7\0\0\0\0\0"
          "analytics.MetricResponse"
          "message"}},
    };
  }

  inline constexpr MetricResponse::Impl_::Impl_(
      [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
      ::_pbi::ConstantInitialized) noexcept
      : message_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        success_{false} {}

  template <typename>
  constexpr MetricResponse::MetricResponse(::_pbi::ConstantInitialized,
                                           const ::_pbi::ClassData *PROTOBUF_NONNULL class_data)
      : Super_(
#if defined(PROTOBUF_CUSTOM_VTABLE)
            class_data
#endif // PROTOBUF_CUSTOM_VTABLE
            ),
        _impl_(internal_visibility(), ::_pbi::ConstantInitialized())
  {
  }
  inline void *PROTOBUF_NONNULL MetricResponse::PlacementNew_(
      const void *PROTOBUF_NONNULL, void *PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena *PROTOBUF_NULLABLE arena)
  {
    return ::new (mem) MetricResponse(arena);
  }
  constexpr auto MetricResponse::InternalNewImpl_()
  {
    return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(MetricResponse), alignof(MetricResponse));
  }
  constexpr auto MetricResponse::InternalGenerateClassData_(
      const MessageLite &prototype,
      const ::google::protobuf::internal::TcParseTableBase *tc_table)
  {
    return ::google::protobuf::internal::ClassDataFull{
        ::google::protobuf::internal::ClassData{
            &prototype,
#ifndef PROTOBUF_MESSAGE_GLOBALS
            &_table_.header,
#else
            tc_table,
#endif
            nullptr, // IsInitialized
            &MetricResponse::MergeImpl,
            Super_::GetNewImpl<MetricResponse>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
            &MetricResponse::SharedDtor,
            Super_::GetClearImpl<MetricResponse>(),
            &MetricResponse::ByteSizeLong,
            &MetricResponse::_InternalSerialize,
#endif // PROTOBUF_CUSTOM_VTABLE
            PROTOBUF_FIELD_OFFSET(MetricResponse, _impl_._cached_size_),
            false,
        },
#ifdef PROTOBUF_MESSAGE_GLOBALS
        &file_reflection_data[1],
#else  // !PROTOBUF_MESSAGE_GLOBALS
        &::_pbi::kDescriptorMethods,
        &descriptor_table_gRPCAnalytics_2eproto,
        nullptr, // tracker
#endif // PROTOBUF_MESSAGE_GLOBALS
    };
  }
  struct MetricResponseGlobalsTypeInternal : ::_pbi::MessageGlobalsBase
  {
    constexpr MetricResponseGlobalsTypeInternal()
        :
#ifndef PROTOBUF_MESSAGE_GLOBALS
          _default(::_pbi::ConstantInitialized{},
                   MetricResponse_class_data_.base())
#else  // !PROTOBUF_MESSAGE_GLOBALS
          MessageGlobalsBase(MetricResponse::InternalGenerateClassData_(
              _default, &MetricResponse_globals_._table.header)),
          _default(::_pbi::ConstantInitialized{}, GetClassData()),
          _table(::_pbi::PrivateAccess::GenerateParseTable<MetricResponse>(
              GetClassData()))
#endif // PROTOBUF_MESSAGE_GLOBALS
    {
    }
    ~MetricResponseGlobalsTypeInternal() {}
    union
    {
      alignas(::_pbi::kMaxMessageAlignment) MetricResponse _default;
    };
#ifdef PROTOBUF_MESSAGE_GLOBALS
    decltype(::_pbi::PrivateAccess::GenerateParseTable<MetricResponse>(
        ::std::declval<const ::_pbi::ClassData *>())) _table;
#endif
  };
#ifdef PROTOBUF_MESSAGE_GLOBALS
  static_assert(PROTOBUF_FIELD_OFFSET(MetricResponseGlobalsTypeInternal, _default) ==
                ::_pbi::MessageGlobalsBase::OffsetToDefault());
#endif // PROTOBUF_MESSAGE_GLOBALS

  PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
      PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PROTOBUF_MESSAGE_GLOBALS_CONST MetricResponseGlobalsTypeInternal MetricResponse_globals_
          PROTOBUF_MESSAGE_GLOBALS_SECTION(.data.rel.ro);
#if defined(PROTOBUF_CUSTOM_VTABLE)
  namespace
  {
    const ::_pbi::ClassData *MetricResponse_get_class_data()
    {
#ifdef PROTOBUF_MESSAGE_GLOBALS
      return MetricResponse_globals_.GetClassData();
#else
      return MetricResponse_class_data_.base();
#endif // PROTOBUF_MESSAGE_GLOBALS
    }
  } // namespace
#endif // PROTOBUF_CUSTOM_VTABLE
  class MetricRequest::_Internal
  {
  public:
    using HasBits = decltype(::std::declval<MetricRequest>()._impl_._has_bits_);
    static constexpr ::int32_t kHasBitsOffset =
        8 * PROTOBUF_FIELD_OFFSET(MetricRequest, _impl_._has_bits_);
  };

  constexpr MetricRequest::ParseTableT_ MetricRequest::InternalGenerateParseTable_(const ::_pbi::ClassData *class_data)
  {
    return ParseTableT_{
        {
            PROTOBUF_FIELD_OFFSET(MetricRequest, _impl_._has_bits_),
            0, // no _extensions_
            3,
            24, // max_field_number, fast_idx_mask
            offsetof(ParseTableT_, field_lookup_table),
            4294967288, // skipmap
            offsetof(ParseTableT_, field_entries),
            3,                                   // num_field_entries
            0,                                   // num_aux_entries
            offsetof(ParseTableT_, field_names), // no aux_entries
            class_data,
            nullptr,                           // post_loop_handler
            ::_pbi::TcParser::MpUnknownFields, // fallback
#ifdef PROTOBUF_PREFETCH_PARSE_TABLE
            ::_pbi::TcParser::GetTable<::analytics::MetricRequest>(), // to_prefetch
#endif                                                                // PROTOBUF_PREFETCH_PARSE_TABLE
        },
        {{
            {::_pbi::TcParser::MiniParse, {}},
            // string device_id = 1;
            {::_pbi::TcParser::FastUS1,
             {10, 0, 0,
              PROTOBUF_FIELD_OFFSET(MetricRequest, _impl_.device_id_)}},
            // double reading_value = 2;
            {::_pbi::TcParser::FastF64S1,
             {17, 1, 0,
              PROTOBUF_FIELD_OFFSET(MetricRequest, _impl_.reading_value_)}},
            // int64 timestamp = 3;
            {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(MetricRequest, _impl_.timestamp_), 2>(),
             {24, 2, 0,
              PROTOBUF_FIELD_OFFSET(MetricRequest, _impl_.timestamp_)}},
        }},
        {{65535, 65535}},
        {{
            // string device_id = 1;
            {PROTOBUF_FIELD_OFFSET(MetricRequest, _impl_.device_id_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
            // double reading_value = 2;
            {PROTOBUF_FIELD_OFFSET(MetricRequest, _impl_.reading_value_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kDouble)},
            // int64 timestamp = 3;
            {PROTOBUF_FIELD_OFFSET(MetricRequest, _impl_.timestamp_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt64)},
        }},
        // no aux_entries
        {{"\27\11\0\0\0\0\0\0"
          "analytics.MetricRequest"
          "device_id"}},
    };
  }

  inline constexpr MetricRequest::Impl_::Impl_(
      [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
      ::_pbi::ConstantInitialized) noexcept
      : device_id_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        reading_value_{0},
        timestamp_{::int64_t{0}} {}

  template <typename>
  constexpr MetricRequest::MetricRequest(::_pbi::ConstantInitialized,
                                         const ::_pbi::ClassData *PROTOBUF_NONNULL class_data)
      : Super_(
#if defined(PROTOBUF_CUSTOM_VTABLE)
            class_data
#endif // PROTOBUF_CUSTOM_VTABLE
            ),
        _impl_(internal_visibility(), ::_pbi::ConstantInitialized())
  {
  }
  inline void *PROTOBUF_NONNULL MetricRequest::PlacementNew_(
      const void *PROTOBUF_NONNULL, void *PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena *PROTOBUF_NULLABLE arena)
  {
    return ::new (mem) MetricRequest(arena);
  }
  constexpr auto MetricRequest::InternalNewImpl_()
  {
    return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(MetricRequest), alignof(MetricRequest));
  }
  constexpr auto MetricRequest::InternalGenerateClassData_(
      const MessageLite &prototype,
      const ::google::protobuf::internal::TcParseTableBase *tc_table)
  {
    return ::google::protobuf::internal::ClassDataFull{
        ::google::protobuf::internal::ClassData{
            &prototype,
#ifndef PROTOBUF_MESSAGE_GLOBALS
            &_table_.header,
#else
            tc_table,
#endif
            nullptr, // IsInitialized
            &MetricRequest::MergeImpl,
            Super_::GetNewImpl<MetricRequest>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
            &MetricRequest::SharedDtor,
            Super_::GetClearImpl<MetricRequest>(),
            &MetricRequest::ByteSizeLong,
            &MetricRequest::_InternalSerialize,
#endif // PROTOBUF_CUSTOM_VTABLE
            PROTOBUF_FIELD_OFFSET(MetricRequest, _impl_._cached_size_),
            false,
        },
#ifdef PROTOBUF_MESSAGE_GLOBALS
        &file_reflection_data[0],
#else  // !PROTOBUF_MESSAGE_GLOBALS
        &::_pbi::kDescriptorMethods,
        &descriptor_table_gRPCAnalytics_2eproto,
        nullptr, // tracker
#endif // PROTOBUF_MESSAGE_GLOBALS
    };
  }
  struct MetricRequestGlobalsTypeInternal : ::_pbi::MessageGlobalsBase
  {
    constexpr MetricRequestGlobalsTypeInternal()
        :
#ifndef PROTOBUF_MESSAGE_GLOBALS
          _default(::_pbi::ConstantInitialized{},
                   MetricRequest_class_data_.base())
#else  // !PROTOBUF_MESSAGE_GLOBALS
          MessageGlobalsBase(MetricRequest::InternalGenerateClassData_(
              _default, &MetricRequest_globals_._table.header)),
          _default(::_pbi::ConstantInitialized{}, GetClassData()),
          _table(::_pbi::PrivateAccess::GenerateParseTable<MetricRequest>(
              GetClassData()))
#endif // PROTOBUF_MESSAGE_GLOBALS
    {
    }
    ~MetricRequestGlobalsTypeInternal() {}
    union
    {
      alignas(::_pbi::kMaxMessageAlignment) MetricRequest _default;
    };
#ifdef PROTOBUF_MESSAGE_GLOBALS
    decltype(::_pbi::PrivateAccess::GenerateParseTable<MetricRequest>(
        ::std::declval<const ::_pbi::ClassData *>())) _table;
#endif
  };
#ifdef PROTOBUF_MESSAGE_GLOBALS
  static_assert(PROTOBUF_FIELD_OFFSET(MetricRequestGlobalsTypeInternal, _default) ==
                ::_pbi::MessageGlobalsBase::OffsetToDefault());
#endif // PROTOBUF_MESSAGE_GLOBALS

  PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
      PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PROTOBUF_MESSAGE_GLOBALS_CONST MetricRequestGlobalsTypeInternal MetricRequest_globals_
          PROTOBUF_MESSAGE_GLOBALS_SECTION(.data.rel.ro);
#if defined(PROTOBUF_CUSTOM_VTABLE)
  namespace
  {
    const ::_pbi::ClassData *MetricRequest_get_class_data()
    {
#ifdef PROTOBUF_MESSAGE_GLOBALS
      return MetricRequest_globals_.GetClassData();
#else
      return MetricRequest_class_data_.base();
#endif // PROTOBUF_MESSAGE_GLOBALS
    }
  } // namespace
#endif // PROTOBUF_CUSTOM_VTABLE
} // namespace analytics
static constexpr const ::_pb::EnumDescriptor *PROTOBUF_NONNULL *PROTOBUF_NULLABLE
    file_level_enum_descriptors_gRPCAnalytics_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor *PROTOBUF_NONNULL *PROTOBUF_NULLABLE
    file_level_service_descriptors_gRPCAnalytics_2eproto = nullptr;
const ::uint32_t
    TableStruct_gRPCAnalytics_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::analytics::MetricRequest, _impl_._has_bits_),
        6, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::analytics::MetricRequest, _impl_.device_id_),
        PROTOBUF_FIELD_OFFSET(::analytics::MetricRequest, _impl_.reading_value_),
        PROTOBUF_FIELD_OFFSET(::analytics::MetricRequest, _impl_.timestamp_),
        0,
        1,
        2,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::analytics::MetricResponse, _impl_._has_bits_),
        5, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::analytics::MetricResponse, _impl_.success_),
        PROTOBUF_FIELD_OFFSET(::analytics::MetricResponse, _impl_.message_),
        1,
        0,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::analytics::MetricRequest)},
        {9, sizeof(::analytics::MetricResponse)},
};
static const ::_pbi::MessageGlobalsBase *PROTOBUF_NONNULL const
    file_message_globals[] = {
        &::analytics::MetricRequest_globals_,
        &::analytics::MetricResponse_globals_,
};
const char descriptor_table_protodef_gRPCAnalytics_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\023gRPCAnalytics.proto\022\tanalytics\"L\n\rMetr"
    "icRequest\022\021\n\tdevice_id\030\001 \001(\t\022\025\n\rreading_"
    "value\030\002 \001(\001\022\021\n\ttimestamp\030\003 \001(\003\"2\n\016Metric"
    "Response\022\017\n\007success\030\001 \001(\010\022\017\n\007message\030\002 \001"
    "(\t2U\n\020AnalyticsService\022A\n\nSendMetric\022\030.a"
    "nalytics.MetricRequest\032\031.analytics.Metri"
    "cResponseb\006proto3"};
static ::absl::once_flag descriptor_table_gRPCAnalytics_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_gRPCAnalytics_2eproto = {
    false,
    false,
    257,
    descriptor_table_protodef_gRPCAnalytics_2eproto,
    "gRPCAnalytics.proto",
    &descriptor_table_gRPCAnalytics_2eproto_once,
    nullptr,
    0,
    2,
    schemas,
    file_message_globals,
    TableStruct_gRPCAnalytics_2eproto::offsets,
    file_level_enum_descriptors_gRPCAnalytics_2eproto,
    file_level_service_descriptors_gRPCAnalytics_2eproto,
};
namespace analytics
{
  // ===================================================================

  MetricRequest::MetricRequest(::google::protobuf::Arena *PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
      : Super_(arena, MetricRequest_get_class_data())
  {
#else  // PROTOBUF_CUSTOM_VTABLE
      : Super_(arena)
  {
#endif // PROTOBUF_CUSTOM_VTABLE
    SharedCtor(arena);
    // @@protoc_insertion_point(arena_constructor:analytics.MetricRequest)
  }
  PROTOBUF_NDEBUG_INLINE MetricRequest::Impl_::Impl_(
      [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
      [[maybe_unused]] ::google::protobuf::Arena *PROTOBUF_NULLABLE arena, const Impl_ &from,
      [[maybe_unused]] const ::analytics::MetricRequest &from_msg)
      : _has_bits_{from._has_bits_},
        device_id_(arena, from.device_id_) {}

  MetricRequest::MetricRequest(
      ::google::protobuf::Arena *PROTOBUF_NULLABLE arena,
      const MetricRequest &from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
      : Super_(arena, MetricRequest_get_class_data())
  {

#else  // PROTOBUF_CUSTOM_VTABLE
      : Super_(arena)
  {
#endif // PROTOBUF_CUSTOM_VTABLE
    MetricRequest *const _this = this;
    (void)_this;
    _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
        from._internal_metadata_);
    new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
    ::memcpy(reinterpret_cast<char *>(&_impl_) +
                 offsetof(Impl_, reading_value_),
             reinterpret_cast<const char *>(&from._impl_) +
                 offsetof(Impl_, reading_value_),
             offsetof(Impl_, timestamp_) -
                 offsetof(Impl_, reading_value_) +
                 sizeof(Impl_::timestamp_));

    // @@protoc_insertion_point(copy_constructor:analytics.MetricRequest)
  }
  PROTOBUF_NDEBUG_INLINE MetricRequest::Impl_::Impl_(
      [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
      [[maybe_unused]] ::google::protobuf::Arena *PROTOBUF_NULLABLE arena)
      : device_id_(arena) {}

  inline void MetricRequest::SharedCtor(::_pb::Arena *PROTOBUF_NULLABLE arena)
  {
    new (&_impl_) Impl_(internal_visibility(), arena);
    ::memset(reinterpret_cast<char *>(&_impl_) +
                 offsetof(Impl_, reading_value_),
             0,
             offsetof(Impl_, timestamp_) -
                 offsetof(Impl_, reading_value_) +
                 sizeof(Impl_::timestamp_));
  }
  MetricRequest::~MetricRequest()
  {
    // @@protoc_insertion_point(destructor:analytics.MetricRequest)
    SharedDtor(*this);
  }
  inline void MetricRequest::SharedDtor(MessageLite &self)
  {
    MetricRequest &this_ = static_cast<MetricRequest &>(self);
    if constexpr (::_pbi::DebugHardenCheckHasBitConsistency())
    {
      this_.CheckHasBitConsistency();
    }
    this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
    ABSL_DCHECK(this_.GetArena() == nullptr);
    this_._impl_.device_id_.Destroy();
    this_._impl_.~Impl_();
  }

#ifndef PROTOBUF_MESSAGE_GLOBALS
  PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const ::google::protobuf::internal::ClassDataFull MetricRequest_class_data_ =
      MetricRequest::InternalGenerateClassData_(MetricRequest_globals_._default);

  PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData *PROTOBUF_NONNULL
  MetricRequest::GetClassData() const
  {
    ::google::protobuf::internal::PrefetchToLocalCache(&MetricRequest_class_data_);
    ::google::protobuf::internal::PrefetchToLocalCache(MetricRequest_class_data_.tc_table);
    return MetricRequest_class_data_.base();
  }
#else
  PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData *PROTOBUF_NONNULL
  MetricRequest::GetClassData() const
  {
    ::google::protobuf::internal::PrefetchToLocalCache(&MetricRequest_globals_);
    ::google::protobuf::internal::PrefetchToLocalCache(
        ::google::protobuf::internal::MessageGlobalsBase::ToParseTableBase(&MetricRequest_globals_));
    return MetricRequest_globals_.GetClassData();
  }
#endif // !PROTOBUF_MESSAGE_GLOBALS
#ifndef PROTOBUF_MESSAGE_GLOBALS
  PROTOBUF_CONSTINIT
  PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const MetricRequest::ParseTableT_
      MetricRequest::_table_ =
          MetricRequest::InternalGenerateParseTable_(MetricRequest_class_data_.base());
#endif // !PROTOBUF_MESSAGE_GLOBALS
  PROTOBUF_NOINLINE void MetricRequest::Clear()
  {
    auto &this_ [[maybe_unused]] = *this;
    // @@protoc_insertion_point(message_clear_start:analytics.MetricRequest)
    ::google::protobuf::internal::TSanWrite(&_impl_);
    ::uint32_t cached_has_bits [[maybe_unused]] = 0;

    cached_has_bits = this_._impl_._has_bits_[0];
    if (CheckHasBit(cached_has_bits, 0x00000001U))
    {
      this_._impl_.device_id_.ClearNonDefaultToEmpty();
    }
    if (BatchCheckHasBit(cached_has_bits, 0x00000006U))
    {
      ::memset(&this_._impl_.reading_value_, 0,
               static_cast<::size_t>(
                   reinterpret_cast<char *>(&this_._impl_.timestamp_) -
                   reinterpret_cast<char *>(&this_._impl_.reading_value_)) +
                   sizeof(_impl_.timestamp_));
    }
    _impl_._has_bits_.Clear();
    _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
  }

#if defined(PROTOBUF_CUSTOM_VTABLE)
  ::uint8_t *PROTOBUF_NONNULL MetricRequest::_InternalSerialize(
      const ::google::protobuf::MessageLite &base, ::uint8_t *PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream *PROTOBUF_NONNULL stream)
  {
    const MetricRequest &this_ = static_cast<const MetricRequest &>(base);
#else  // PROTOBUF_CUSTOM_VTABLE
  ::uint8_t *PROTOBUF_NONNULL MetricRequest::_InternalSerialize(
      ::uint8_t *PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream *PROTOBUF_NONNULL stream) const
  {
    const MetricRequest &this_ = *this;
#endif // PROTOBUF_CUSTOM_VTABLE
    if constexpr (::_pbi::DebugHardenCheckHasBitConsistency())
    {
      this_.CheckHasBitConsistency();
    }
    // @@protoc_insertion_point(serialize_to_array_start:analytics.MetricRequest)
    ::uint32_t cached_has_bits = 0;
    (void)cached_has_bits;

    cached_has_bits = this_._impl_._has_bits_[0];
    // string device_id = 1;
    if (CheckHasBit(cached_has_bits, 0x00000001U))
    {
      if (!this_._internal_device_id().empty())
      {
        const ::std::string &_s = this_._internal_device_id();
        ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "analytics.MetricRequest.device_id");
        target = stream->WriteStringMaybeAliased(1, _s, target);
      }
    }

    // double reading_value = 2;
    if (CheckHasBit(cached_has_bits, 0x00000002U))
    {
      if (::absl::bit_cast<::uint64_t>(this_._internal_reading_value()) != 0)
      {
        target = stream->EnsureSpace(target);
        target = ::_pbi::WireFormatLite::WriteDoubleToArray(
            2, this_._internal_reading_value(), target);
      }
    }

    // int64 timestamp = 3;
    if (CheckHasBit(cached_has_bits, 0x00000004U))
    {
      if (this_._internal_timestamp() != 0)
      {
        target =
            ::google::protobuf::internal::WireFormatLite::WriteInt64ToArrayWithField<3>(
                stream, this_._internal_timestamp(), target);
      }
    }

    if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields()))
    {
      target =
          ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
              this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
    }
    // @@protoc_insertion_point(serialize_to_array_end:analytics.MetricRequest)
    return target;
  }

#if defined(PROTOBUF_CUSTOM_VTABLE)
  ::size_t MetricRequest::ByteSizeLong(const MessageLite &base)
  {
    const MetricRequest &this_ = static_cast<const MetricRequest &>(base);
#else  // PROTOBUF_CUSTOM_VTABLE
  ::size_t MetricRequest::ByteSizeLong() const
  {
    const MetricRequest &this_ = *this;
#endif // PROTOBUF_CUSTOM_VTABLE
    // @@protoc_insertion_point(message_byte_size_start:analytics.MetricRequest)
    ::size_t total_size = 0;

    ::uint32_t cached_has_bits [[maybe_unused]] = 0;

    ::_pbi::Prefetch5LinesFrom7Lines(&this_);
    cached_has_bits = this_._impl_._has_bits_[0];
    if (BatchCheckHasBit(cached_has_bits, 0x00000007U))
    {
      // string device_id = 1;
      if (CheckHasBit(cached_has_bits, 0x00000001U))
      {
        if (!this_._internal_device_id().empty())
        {
          total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                this_._internal_device_id());
        }
      }
      // double reading_value = 2;
      if (CheckHasBit(cached_has_bits, 0x00000002U))
      {
        if (::absl::bit_cast<::uint64_t>(this_._internal_reading_value()) != 0)
        {
          total_size += 9;
        }
      }
      // int64 timestamp = 3;
      if (CheckHasBit(cached_has_bits, 0x00000004U))
      {
        if (this_._internal_timestamp() != 0)
        {
          total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
              this_._internal_timestamp());
        }
      }
    }
    return this_.MaybeComputeUnknownFieldsSize(total_size,
                                               &this_._impl_._cached_size_);
  }

  void MetricRequest::MergeImpl(::google::protobuf::MessageLite &to_msg,
                                const ::google::protobuf::MessageLite &from_msg)
  {
    auto *const _this = static_cast<MetricRequest *>(&to_msg);
    auto &from = static_cast<const MetricRequest &>(from_msg);
    if constexpr (::_pbi::DebugHardenCheckHasBitConsistency())
    {
      from.CheckHasBitConsistency();
    }
    // @@protoc_insertion_point(class_specific_merge_from_start:analytics.MetricRequest)
    ABSL_DCHECK_NE(&from, _this);
    ::uint32_t cached_has_bits = 0;
    (void)cached_has_bits;

    cached_has_bits = from._impl_._has_bits_[0];
    if (BatchCheckHasBit(cached_has_bits, 0x00000007U))
    {
      if (CheckHasBit(cached_has_bits, 0x00000001U))
      {
        if (!from._internal_device_id().empty())
        {
          _this->_internal_set_device_id(from._internal_device_id());
        }
        else
        {
          if (_this->_impl_.device_id_.IsDefault())
          {
            _this->_internal_set_device_id("");
          }
        }
      }
      if (CheckHasBit(cached_has_bits, 0x00000002U))
      {
        if (::absl::bit_cast<::uint64_t>(from._internal_reading_value()) != 0)
        {
          _this->_impl_.reading_value_ = from._impl_.reading_value_;
        }
      }
      if (CheckHasBit(cached_has_bits, 0x00000004U))
      {
        if (from._internal_timestamp() != 0)
        {
          _this->_impl_.timestamp_ = from._impl_.timestamp_;
        }
      }
    }
    _this->_impl_._has_bits_[0] |= cached_has_bits;
    _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
        from._internal_metadata_);
  }

  void MetricRequest::CopyFrom(const MetricRequest &from)
  {
    // @@protoc_insertion_point(class_specific_copy_from_start:analytics.MetricRequest)
    if (&from == this)
      return;
    Clear();
    MergeFrom(from);
  }

  void MetricRequest::InternalSwap(MetricRequest *PROTOBUF_RESTRICT PROTOBUF_NONNULL other)
  {
    using ::std::swap;
    auto *arena = GetArena();
    ABSL_DCHECK_EQ(arena, other->GetArena());
    _internal_metadata_.InternalSwap(&other->_internal_metadata_);
    swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
    ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.device_id_, &other->_impl_.device_id_, arena);
    ::google::protobuf::internal::memswap<
        PROTOBUF_FIELD_OFFSET(MetricRequest, _impl_.timestamp_) + sizeof(MetricRequest::_impl_.timestamp_) - PROTOBUF_FIELD_OFFSET(MetricRequest, _impl_.reading_value_)>(
        reinterpret_cast<char *>(&_impl_.reading_value_),
        reinterpret_cast<char *>(&other->_impl_.reading_value_));
  }

  ::google::protobuf::Metadata MetricRequest::GetMetadata() const
  {
    return Super_::GetMetadataImpl(GetClassData()->full());
  }
  // ===================================================================

  MetricResponse::MetricResponse(::google::protobuf::Arena *PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
      : Super_(arena, MetricResponse_get_class_data())
  {
#else  // PROTOBUF_CUSTOM_VTABLE
      : Super_(arena)
  {
#endif // PROTOBUF_CUSTOM_VTABLE
    SharedCtor(arena);
    // @@protoc_insertion_point(arena_constructor:analytics.MetricResponse)
  }
  PROTOBUF_NDEBUG_INLINE MetricResponse::Impl_::Impl_(
      [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
      [[maybe_unused]] ::google::protobuf::Arena *PROTOBUF_NULLABLE arena, const Impl_ &from,
      [[maybe_unused]] const ::analytics::MetricResponse &from_msg)
      : _has_bits_{from._has_bits_},
        message_(arena, from.message_) {}

  MetricResponse::MetricResponse(
      ::google::protobuf::Arena *PROTOBUF_NULLABLE arena,
      const MetricResponse &from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
      : Super_(arena, MetricResponse_get_class_data())
  {

#else  // PROTOBUF_CUSTOM_VTABLE
      : Super_(arena)
  {
#endif // PROTOBUF_CUSTOM_VTABLE
    MetricResponse *const _this = this;
    (void)_this;
    _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
        from._internal_metadata_);
    new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
    _impl_.success_ = from._impl_.success_;

    // @@protoc_insertion_point(copy_constructor:analytics.MetricResponse)
  }
  PROTOBUF_NDEBUG_INLINE MetricResponse::Impl_::Impl_(
      [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
      [[maybe_unused]] ::google::protobuf::Arena *PROTOBUF_NULLABLE arena)
      : message_(arena) {}

  inline void MetricResponse::SharedCtor(::_pb::Arena *PROTOBUF_NULLABLE arena)
  {
    new (&_impl_) Impl_(internal_visibility(), arena);
    _impl_.success_ = {};
  }
  MetricResponse::~MetricResponse()
  {
    // @@protoc_insertion_point(destructor:analytics.MetricResponse)
    SharedDtor(*this);
  }
  inline void MetricResponse::SharedDtor(MessageLite &self)
  {
    MetricResponse &this_ = static_cast<MetricResponse &>(self);
    if constexpr (::_pbi::DebugHardenCheckHasBitConsistency())
    {
      this_.CheckHasBitConsistency();
    }
    this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
    ABSL_DCHECK(this_.GetArena() == nullptr);
    this_._impl_.message_.Destroy();
    this_._impl_.~Impl_();
  }

#ifndef PROTOBUF_MESSAGE_GLOBALS
  PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const ::google::protobuf::internal::ClassDataFull MetricResponse_class_data_ =
      MetricResponse::InternalGenerateClassData_(MetricResponse_globals_._default);

  PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData *PROTOBUF_NONNULL
  MetricResponse::GetClassData() const
  {
    ::google::protobuf::internal::PrefetchToLocalCache(&MetricResponse_class_data_);
    ::google::protobuf::internal::PrefetchToLocalCache(MetricResponse_class_data_.tc_table);
    return MetricResponse_class_data_.base();
  }
#else
  PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData *PROTOBUF_NONNULL
  MetricResponse::GetClassData() const
  {
    ::google::protobuf::internal::PrefetchToLocalCache(&MetricResponse_globals_);
    ::google::protobuf::internal::PrefetchToLocalCache(
        ::google::protobuf::internal::MessageGlobalsBase::ToParseTableBase(&MetricResponse_globals_));
    return MetricResponse_globals_.GetClassData();
  }
#endif // !PROTOBUF_MESSAGE_GLOBALS
#ifndef PROTOBUF_MESSAGE_GLOBALS
  PROTOBUF_CONSTINIT
  PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const MetricResponse::ParseTableT_
      MetricResponse::_table_ =
          MetricResponse::InternalGenerateParseTable_(MetricResponse_class_data_.base());
#endif // !PROTOBUF_MESSAGE_GLOBALS
  PROTOBUF_NOINLINE void MetricResponse::Clear()
  {
    auto &this_ [[maybe_unused]] = *this;
    // @@protoc_insertion_point(message_clear_start:analytics.MetricResponse)
    ::google::protobuf::internal::TSanWrite(&_impl_);
    ::uint32_t cached_has_bits [[maybe_unused]] = 0;

    cached_has_bits = this_._impl_._has_bits_[0];
    if (CheckHasBit(cached_has_bits, 0x00000001U))
    {
      this_._impl_.message_.ClearNonDefaultToEmpty();
    }
    this_._impl_.success_ = false;
    _impl_._has_bits_.Clear();
    _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
  }

#if defined(PROTOBUF_CUSTOM_VTABLE)
  ::uint8_t *PROTOBUF_NONNULL MetricResponse::_InternalSerialize(
      const ::google::protobuf::MessageLite &base, ::uint8_t *PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream *PROTOBUF_NONNULL stream)
  {
    const MetricResponse &this_ = static_cast<const MetricResponse &>(base);
#else  // PROTOBUF_CUSTOM_VTABLE
  ::uint8_t *PROTOBUF_NONNULL MetricResponse::_InternalSerialize(
      ::uint8_t *PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream *PROTOBUF_NONNULL stream) const
  {
    const MetricResponse &this_ = *this;
#endif // PROTOBUF_CUSTOM_VTABLE
    if constexpr (::_pbi::DebugHardenCheckHasBitConsistency())
    {
      this_.CheckHasBitConsistency();
    }
    // @@protoc_insertion_point(serialize_to_array_start:analytics.MetricResponse)
    ::uint32_t cached_has_bits = 0;
    (void)cached_has_bits;

    cached_has_bits = this_._impl_._has_bits_[0];
    // bool success = 1;
    if (CheckHasBit(cached_has_bits, 0x00000002U))
    {
      if (this_._internal_success() != 0)
      {
        target = stream->EnsureSpace(target);
        target = ::_pbi::WireFormatLite::WriteBoolToArray(
            1, this_._internal_success(), target);
      }
    }

    // string message = 2;
    if (CheckHasBit(cached_has_bits, 0x00000001U))
    {
      if (!this_._internal_message().empty())
      {
        const ::std::string &_s = this_._internal_message();
        ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "analytics.MetricResponse.message");
        target = stream->WriteStringMaybeAliased(2, _s, target);
      }
    }

    if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields()))
    {
      target =
          ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
              this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
    }
    // @@protoc_insertion_point(serialize_to_array_end:analytics.MetricResponse)
    return target;
  }

#if defined(PROTOBUF_CUSTOM_VTABLE)
  ::size_t MetricResponse::ByteSizeLong(const MessageLite &base)
  {
    const MetricResponse &this_ = static_cast<const MetricResponse &>(base);
#else  // PROTOBUF_CUSTOM_VTABLE
  ::size_t MetricResponse::ByteSizeLong() const
  {
    const MetricResponse &this_ = *this;
#endif // PROTOBUF_CUSTOM_VTABLE
    // @@protoc_insertion_point(message_byte_size_start:analytics.MetricResponse)
    ::size_t total_size = 0;

    ::uint32_t cached_has_bits [[maybe_unused]] = 0;

    ::_pbi::Prefetch5LinesFrom7Lines(&this_);
    cached_has_bits = this_._impl_._has_bits_[0];
    if (BatchCheckHasBit(cached_has_bits, 0x00000003U))
    {
      // string message = 2;
      if (CheckHasBit(cached_has_bits, 0x00000001U))
      {
        if (!this_._internal_message().empty())
        {
          total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                this_._internal_message());
        }
      }
      // bool success = 1;
      if (CheckHasBit(cached_has_bits, 0x00000002U))
      {
        if (this_._internal_success() != 0)
        {
          total_size += 2;
        }
      }
    }
    return this_.MaybeComputeUnknownFieldsSize(total_size,
                                               &this_._impl_._cached_size_);
  }

  void MetricResponse::MergeImpl(::google::protobuf::MessageLite &to_msg,
                                 const ::google::protobuf::MessageLite &from_msg)
  {
    auto *const _this = static_cast<MetricResponse *>(&to_msg);
    auto &from = static_cast<const MetricResponse &>(from_msg);
    if constexpr (::_pbi::DebugHardenCheckHasBitConsistency())
    {
      from.CheckHasBitConsistency();
    }
    // @@protoc_insertion_point(class_specific_merge_from_start:analytics.MetricResponse)
    ABSL_DCHECK_NE(&from, _this);
    ::uint32_t cached_has_bits = 0;
    (void)cached_has_bits;

    cached_has_bits = from._impl_._has_bits_[0];
    if (BatchCheckHasBit(cached_has_bits, 0x00000003U))
    {
      if (CheckHasBit(cached_has_bits, 0x00000001U))
      {
        if (!from._internal_message().empty())
        {
          _this->_internal_set_message(from._internal_message());
        }
        else
        {
          if (_this->_impl_.message_.IsDefault())
          {
            _this->_internal_set_message("");
          }
        }
      }
      if (CheckHasBit(cached_has_bits, 0x00000002U))
      {
        if (from._internal_success() != 0)
        {
          _this->_impl_.success_ = from._impl_.success_;
        }
      }
    }
    _this->_impl_._has_bits_[0] |= cached_has_bits;
    _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
        from._internal_metadata_);
  }

  void MetricResponse::CopyFrom(const MetricResponse &from)
  {
    // @@protoc_insertion_point(class_specific_copy_from_start:analytics.MetricResponse)
    if (&from == this)
      return;
    Clear();
    MergeFrom(from);
  }

  void MetricResponse::InternalSwap(MetricResponse *PROTOBUF_RESTRICT PROTOBUF_NONNULL other)
  {
    using ::std::swap;
    auto *arena = GetArena();
    ABSL_DCHECK_EQ(arena, other->GetArena());
    _internal_metadata_.InternalSwap(&other->_internal_metadata_);
    swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
    ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.message_, &other->_impl_.message_, arena);
    swap(_impl_.success_, other->_impl_.success_);
  }

  ::google::protobuf::Metadata MetricResponse::GetMetadata() const
  {
    return Super_::GetMetadataImpl(GetClassData()->full());
  }
  // @@protoc_insertion_point(namespace_scope)
} // namespace analytics
namespace google
{
  namespace protobuf
  {
  } // namespace protobuf
} // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_gRPCAnalytics_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
